chore(deps): update all non-major dependencies (#7363)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [jest](https://jestjs.io/)
([source](https://togithub.com/facebook/jest)) | [`29.4.1` ->
`29.4.2`](https://renovatebot.com/diffs/npm/jest/29.4.1/29.4.2) |
[![age](https://badges.renovateapi.com/packages/npm/jest/29.4.2/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/jest/29.4.2/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/jest/29.4.2/compatibility-slim/29.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/jest/29.4.2/confidence-slim/29.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
| [jest-config](https://togithub.com/facebook/jest) | [`29.4.1` ->
`29.4.2`](https://renovatebot.com/diffs/npm/jest-config/29.4.1/29.4.2) |
[![age](https://badges.renovateapi.com/packages/npm/jest-config/29.4.2/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/jest-config/29.4.2/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/jest-config/29.4.2/compatibility-slim/29.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/jest-config/29.4.2/confidence-slim/29.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
| [jest-mock](https://togithub.com/facebook/jest) | [`29.4.1` ->
`29.4.2`](https://renovatebot.com/diffs/npm/jest-mock/29.4.1/29.4.2) |
[![age](https://badges.renovateapi.com/packages/npm/jest-mock/29.4.2/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/jest-mock/29.4.2/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/jest-mock/29.4.2/compatibility-slim/29.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/jest-mock/29.4.2/confidence-slim/29.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
| [npm](https://docs.npmjs.com/)
([source](https://togithub.com/npm/cli)) | [`9.4.1` ->
`9.4.2`](https://renovatebot.com/diffs/npm/npm/9.4.1/9.4.2) |
[![age](https://badges.renovateapi.com/packages/npm/npm/9.4.2/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/npm/9.4.2/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/npm/9.4.2/compatibility-slim/9.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/npm/9.4.2/confidence-slim/9.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`2.8.3` ->
`2.8.4`](https://renovatebot.com/diffs/npm/prettier/2.8.3/2.8.4) |
[![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.4/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.4/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.4/compatibility-slim/2.8.3)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.4/confidence-slim/2.8.3)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>facebook/jest</summary>

###
[`v29.4.2`](https://togithub.com/facebook/jest/blob/HEAD/CHANGELOG.md#&#8203;2942)

[Compare
Source](https://togithub.com/facebook/jest/compare/v29.4.1...v29.4.2)

##### Features

- `[@jest/core]` Instrument significant lifecycle events with
[`performance.mark()`](https://nodejs.org/docs/latest-v16.x/api/perf_hooks.html#performancemarkname-options)
([#&#8203;13859](https://togithub.com/facebook/jest/pull/13859))

##### Fixes

- `[expect, @&#8203;jest/expect]` Provide type of `actual` as a generic
argument to `Matchers` to allow better-typed extensions
([#&#8203;13848](https://togithub.com/facebook/jest/pull/13848))
- `[jest-circus]` Added explicit mention of test failing because
`done()` is not being called in error message
([#&#8203;13847](https://togithub.com/facebook/jest/pull/13847))
- `[jest-runtime]` Handle CJS re-exports of node core modules from ESM
([#&#8203;13856](https://togithub.com/facebook/jest/pull/13856))
- `[jest-transform]` Downgrade `write-file-atomic` to v4
([#&#8203;13853](https://togithub.com/facebook/jest/pull/13853))
- `[jest-worker]` Ignore IPC messages not intended for Jest
([#&#8203;13543](https://togithub.com/facebook/jest/pull/13543))

##### Chore & Maintenance

- `[*]` make sure to exclude `.eslintcache` from published module
([#&#8203;13832](https://togithub.com/facebook/jest/pull/13832))
- `[docs]` Cleanup incorrect links in CHANGELOG.md
([#&#8203;13857](https://togithub.com/facebook/jest/pull/13857))

</details>

<details>
<summary>npm/cli</summary>

###
[`v9.4.2`](https://togithub.com/npm/cli/blob/HEAD/CHANGELOG.md#&#8203;942-httpsgithubcomnpmclicomparev941v942-2023-02-07)

[Compare Source](https://togithub.com/npm/cli/compare/v9.4.1...v9.4.2)

##### Bug Fixes

-
[`d02da52`](https://togithub.com/npm/cli/commit/d02da52dc1ac6520223e9e7e8fdcbd9e27b5333f)
[#&#8203;6142](https://togithub.com/npm/cli/pull/6142) revert
`install-links` default back to `false`
([#&#8203;6142](https://togithub.com/npm/cli/issues/6142))
([@&#8203;nlf](https://togithub.com/nlf))

##### Documentation

-
[`6ea2cd7`](https://togithub.com/npm/cli/commit/6ea2cd77c6ba92f213e4833c746f032ef9bfcc3d)
[#&#8203;6134](https://togithub.com/npm/cli/pull/6134) update references
to OTP to be accurate
([#&#8203;6134](https://togithub.com/npm/cli/issues/6134))
([@&#8203;MylesBorins](https://togithub.com/MylesBorins))

##### Dependencies

-
[`cb6713d`](https://togithub.com/npm/cli/commit/cb6713dc8ef7161c8162cc418a023d25b17e5bcf)
[#&#8203;6143](https://togithub.com/npm/cli/pull/6143) rebuild
package-lock ([#&#8203;6143](https://togithub.com/npm/cli/issues/6143))
-
[`8200f4f`](https://togithub.com/npm/cli/commit/8200f4f16d9dad1d44094c8c2182e26bc1a8b732)
[#&#8203;6133](https://togithub.com/npm/cli/pull/6133)
`ignore-walk@6.0.1`
-
[`d43f881`](https://togithub.com/npm/cli/commit/d43f8812af5900cce45364729871a745b379aea9)
`map-workspaces@3.0.2`
-
[`99457f1`](https://togithub.com/npm/cli/commit/99457f1f48d57f913b398e25f4e5da066af71204)
`minimatch@6.1.6`
-
[`f4c8c62`](https://togithub.com/npm/cli/commit/f4c8c62baf532b7599e3760f959788bbda97ba0b)
`init-package-json@5.0.0`
-
[`3c6615f`](https://togithub.com/npm/cli/commit/3c6615fff53a3368679f28b8812eba86dbc195a9)
`npm-user-validate@2.0.0`
-
[`10445ca`](https://togithub.com/npm/cli/commit/10445ca4a09df590777a9289ab1ed0f41449c85d)
remove mkdirp
-
[`ab82492`](https://togithub.com/npm/cli/commit/ab824922ea7678585926adb67a90cdcebc53b4ae)
`node-gyp@9.3.1`
-
[`74c5cbb`](https://togithub.com/npm/cli/commit/74c5cbbd774f7ff7c1f037b382aec36cbc8ca2f1)
`minipass@4.0.2`
-
[`1138038`](https://togithub.com/npm/cli/commit/11380386cef7ad8b12226431ca3d5e166455d626)
`make-fetch-happen@11.0.3`
-
[`c1ccfa1`](https://togithub.com/npm/cli/commit/c1ccfa146523d734bdfe2a7bef1b0abc64e716d8)
`glob@8.1.0`
-
[`3dc17ce`](https://togithub.com/npm/cli/commit/3dc17ce3fa570f9ef2c55e2a565af6fe89b3e73d)
`fs-minipass@3.0.1`
-
[`5c84a99`](https://togithub.com/npm/cli/commit/5c84a99f5a141a632bd644ca97505010c2842eb2)
`ci-info@3.7.1`
-
[`fc5332f`](https://togithub.com/npm/cli/commit/fc5332f4027f3019a855f12a66e29bca1b143364)
`read@2.0.0`
-
[Workspace](https://togithub.com/npm/cli/releases/tag/arborist-v6.2.2):
`@npmcli/arborist@6.2.2`
- [Workspace](https://togithub.com/npm/cli/releases/tag/config-v6.1.3):
`@npmcli/config@6.1.3`
-
[Workspace](https://togithub.com/npm/cli/releases/tag/libnpmdiff-v5.0.10):
`libnpmdiff@5.0.10`
-
[Workspace](https://togithub.com/npm/cli/releases/tag/libnpmexec-v5.0.10):
`libnpmexec@5.0.10`
-
[Workspace](https://togithub.com/npm/cli/releases/tag/libnpmfund-v4.0.10):
`libnpmfund@4.0.10`
-
[Workspace](https://togithub.com/npm/cli/releases/tag/libnpmhook-v9.0.3):
`libnpmhook@9.0.3`
-
[Workspace](https://togithub.com/npm/cli/releases/tag/libnpmorg-v5.0.3):
`libnpmorg@5.0.3`
-
[Workspace](https://togithub.com/npm/cli/releases/tag/libnpmpack-v5.0.10):
`libnpmpack@5.0.10`
-
[Workspace](https://togithub.com/npm/cli/releases/tag/libnpmpublish-v7.0.8):
`libnpmpublish@7.0.8`

</details>

<details>
<summary>prettier/prettier</summary>

###
[`v2.8.4`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;284)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.8.3...2.8.4)

[diff](https://togithub.com/prettier/prettier/compare/2.8.3...2.8.4)

##### Fix leading comments in mapped types with `readonly`
([#&#8203;13427](https://togithub.com/prettier/prettier/pull/13427) by
[@&#8203;thorn0](https://togithub.com/thorn0),
[@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

<!-- prettier-ignore -->

```tsx
// Input
type Type = {
  // comment
  readonly [key in Foo];
};

// Prettier 2.8.3
type Type = {
  readonly // comment
  [key in Foo];
};

// Prettier 2.8.4
type Type = {
  // comment
  readonly [key in Foo];
};
```

##### Group params in opening block statements
([#&#8203;14067](https://togithub.com/prettier/prettier/pull/14067) by
[@&#8203;jamescdavis](https://togithub.com/jamescdavis))

This is a follow-up to
[#&#8203;13930](https://togithub.com/prettier/prettier/issues/13930) to
establish wrapping consistency between opening block statements and else
blocks by
grouping params in opening blocks. This causes params to break to a new
line together and not be split across lines
unless the length of params exceeds the print width. This also updates
the else block wrapping to behave exactly the
same as opening blocks.

<!-- prettier-ignore -->

```hbs
{{! Input }}
{{#block param param param param param param param param param param as |blockParam|}}
  Hello
{{else block param param param param param param param param param param as |blockParam|}}
  There
{{/block}}

{{! Prettier 2.8.3 }}
{{#block
  param
  param
  param
  param
  param
  param
  param
  param
  param
  param
  as |blockParam|
}}
  Hello
{{else block param
param
param
param
param
param
param
param
param
param}}
  There
{{/block}}

{{! Prettier 2.8.4 }}
{{#block
  param param param param param param param param param param
  as |blockParam|
}}
  Hello
{{else block
  param param param param param param param param param param
  as |blockParam|
}}
  There
{{/block}}
```

##### Ignore files in `.sl/`
([#&#8203;14206](https://togithub.com/prettier/prettier/pull/14206) by
[@&#8203;bolinfest](https://togithub.com/bolinfest))

In [Sapling SCM](https://sapling-scm.com/), `.sl/` is the folder where
it stores its state, analogous to `.git/` in Git. It should be ignored
in Prettier like the other SCM folders.

##### Recognize `@satisfies` in Closure-style type casts
([#&#8203;14262](https://togithub.com/prettier/prettier/pull/14262) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
const a = /** @&#8203;satisfies {Record<string, string>} */ ({hello: 1337});
const b = /** @&#8203;type {Record<string, string>} */ ({hello: 1337});

// Prettier 2.8.3
const a = /** @&#8203;satisfies {Record<string, string>} */ { hello: 1337 };
const b = /** @&#8203;type {Record<string, string>} */ ({ hello: 1337 });

// Prettier 2.8.4
const a = /** @&#8203;satisfies {Record<string, string>} */ ({hello: 1337});
const b = /** @&#8203;type {Record<string, string>} */ ({hello: 1337});
```

##### Fix parens in inferred function return types with `extends`
([#&#8203;14279](https://togithub.com/prettier/prettier/pull/14279) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```ts
// Input
type Foo<T> = T extends ((a) => a is infer R extends string) ? R : never;

// Prettier 2.8.3 (First format)
type Foo<T> = T extends (a) => a is infer R extends string ? R : never;

// Prettier 2.8.3 (Second format)
SyntaxError: '?' expected. 

// Prettier 2.8.4
type Foo<T> = T extends ((a) => a is infer R extends string) ? R : never;
```

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://app.renovatebot.com/dashboard#github/apollographql/apollo-server).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNC4xMjQuMiIsInVwZGF0ZWRJblZlciI6IjM0LjEyNC4yIn0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>