chore(deps): update all non-major dependencies (#8090)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[@apollo/gateway](https://redirect.github.com/apollographql/federation)
([source](https://redirect.github.com/apollographql/federation/tree/HEAD/gateway-js/))
| [`2.11.1` ->
`2.11.2`](https://renovatebot.com/diffs/npm/@apollo%2fgateway/2.11.1/2.11.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@apollo%2fgateway/2.11.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@apollo%2fgateway/2.11.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@apollo%2fgateway/2.11.1/2.11.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@apollo%2fgateway/2.11.1/2.11.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@apollo/subgraph](https://redirect.github.com/apollographql/federation)
([source](https://redirect.github.com/apollographql/federation/tree/HEAD/subgraph-js/))
| [`2.11.1` ->
`2.11.2`](https://renovatebot.com/diffs/npm/@apollo%2fsubgraph/2.11.1/2.11.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@apollo%2fsubgraph/2.11.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@apollo%2fsubgraph/2.11.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@apollo%2fsubgraph/2.11.1/2.11.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@apollo%2fsubgraph/2.11.1/2.11.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/lodash](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash)
([source](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/lodash))
| [`4.17.18` ->
`4.17.19`](https://renovatebot.com/diffs/npm/@types%2flodash/4.17.18/4.17.19)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2flodash/4.17.19?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2flodash/4.17.19?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2flodash/4.17.18/4.17.19?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2flodash/4.17.18/4.17.19?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://redirect.github.com/prettier/prettier)) | [`3.6.0` ->
`3.6.1`](https://renovatebot.com/diffs/npm/prettier/3.6.0/3.6.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.6.0/3.6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.6.0/3.6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>apollographql/federation (@&#8203;apollo/gateway)</summary>

###
[`v2.11.2`](https://redirect.github.com/apollographql/federation/blob/HEAD/gateway-js/CHANGELOG.md#2112)

[Compare
Source](https://redirect.github.com/apollographql/federation/compare/@apollo/gateway@2.11.1...@apollo/gateway@2.11.2)

##### Patch Changes

- Updated dependencies
\[[`28c08bef6e691aefc6ed07c0e7057f9cd803b317`](https://redirect.github.com/apollographql/federation/commit/28c08bef6e691aefc6ed07c0e7057f9cd803b317),
[`28c08bef6e691aefc6ed07c0e7057f9cd803b317`](https://redirect.github.com/apollographql/federation/commit/28c08bef6e691aefc6ed07c0e7057f9cd803b317)]:
-
[@&#8203;apollo/federation-internals](https://redirect.github.com/apollo/federation-internals)@&#8203;2.11.2
-
[@&#8203;apollo/composition](https://redirect.github.com/apollo/composition)@&#8203;2.11.2
-
[@&#8203;apollo/query-planner](https://redirect.github.com/apollo/query-planner)@&#8203;2.11.2

</details>

<details>
<summary>apollographql/federation (@&#8203;apollo/subgraph)</summary>

###
[`v2.11.2`](https://redirect.github.com/apollographql/federation/blob/HEAD/subgraph-js/CHANGELOG.md#2112)

[Compare
Source](https://redirect.github.com/apollographql/federation/compare/@apollo/subgraph@2.11.1...@apollo/subgraph@2.11.2)

##### Patch Changes

- Revert change to
[@&#8203;composeDirective](https://redirect.github.com/composeDirective)
definition to specify nullable argument value.
([#&#8203;3283](https://redirect.github.com/apollographql/federation/pull/3283))

We cannot fix the definition as that would break customers using older
versions of `subgraph-js`. Our validations are already verifying that
the values are specified.

- Updated dependencies
\[[`28c08bef6e691aefc6ed07c0e7057f9cd803b317`](https://redirect.github.com/apollographql/federation/commit/28c08bef6e691aefc6ed07c0e7057f9cd803b317)]:
-
[@&#8203;apollo/federation-internals](https://redirect.github.com/apollo/federation-internals)@&#8203;2.11.2

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.6.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#361)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)


[diff](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

##### TypeScript: Allow const without initializer
([#&#8203;17650](https://redirect.github.com/prettier/prettier/pull/17650),
[#&#8203;17654](https://redirect.github.com/prettier/prettier/pull/17654)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
export const version: string;

// Prettier 3.6.0 (--parser=babel-ts)
SyntaxError: Unexpected token (1:21)
> 1 | export const version: string;
    |                     ^

// Prettier 3.6.0 (--parser=oxc-ts)
SyntaxError: Missing initializer in const declaration (1:14)
> 1 | export const version: string;
    |              ^^^^^^^^^^^^^^^

// Prettier 3.6.1
export const version: string;
```

##### Miscellaneous: Avoid closing files multiple times
([#&#8203;17665](https://redirect.github.com/prettier/prettier/pull/17665)
by [@&#8203;43081j](https://redirect.github.com/43081j))

When reading a file to infer the interpreter from a shebang, we use the
`n-readlines` library to read the first line in order to get the
shebang.

This library closes files when it reaches EOF, and we later try close
the same
files again. We now close files only if `n-readlines` did not already
close
them.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/apollographql/apollo-server).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC42Mi4xIiwidXBkYXRlZEluVmVyIjoiNDAuNjIuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiOmNocmlzdG1hc190cmVlOiBkZXBlbmRlbmNpZXMiXX0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>