chore(deps): update all non-major dependencies (#7674)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@apollo/gateway](https://togithub.com/apollographql/federation) |
[`2.5.1` ->
`2.5.2`](https://renovatebot.com/diffs/npm/@apollo%2fgateway/2.5.1/2.5.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@apollo%2fgateway/2.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@apollo%2fgateway/2.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@apollo%2fgateway/2.5.1/2.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@apollo%2fgateway/2.5.1/2.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [@apollo/subgraph](https://togithub.com/apollographql/federation) |
[`2.5.1` ->
`2.5.2`](https://renovatebot.com/diffs/npm/@apollo%2fsubgraph/2.5.1/2.5.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@apollo%2fsubgraph/2.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@apollo%2fsubgraph/2.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@apollo%2fsubgraph/2.5.1/2.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@apollo%2fsubgraph/2.5.1/2.5.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`3.0.0` ->
`3.0.1`](https://renovatebot.com/diffs/npm/prettier/3.0.0/3.0.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.0.0/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.0.0/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [rollup](https://rollupjs.org/)
([source](https://togithub.com/rollup/rollup)) | [`3.27.0` ->
`3.27.2`](https://renovatebot.com/diffs/npm/rollup/3.27.0/3.27.2) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/rollup/3.27.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/rollup/3.27.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/rollup/3.27.0/3.27.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/rollup/3.27.0/3.27.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>apollographql/federation (@&#8203;apollo/gateway)</summary>

###
[`v2.5.2`](https://togithub.com/apollographql/federation/blob/HEAD/gateway-js/CHANGELOG.md#252)

[Compare
Source](https://togithub.com/apollographql/federation/compare/@apollo/gateway@2.5.1...@apollo/gateway@2.5.2)

##### Patch Changes

- Remove extraneous call to `span.setStatus()` on a span which has
already ended.
([#&#8203;2697](https://togithub.com/apollographql/federation/pull/2697))

In cases where a subgraph responded with an error, we would sometimes
try to set
the status of a span which had already ended. This resulted in a warning
log to
the console (but no effect otherwise). This warning should no longer
happen.

- Fix `fallbackPollIntervalInMs` behavior.
([#&#8203;2709](https://togithub.com/apollographql/federation/pull/2709))

    The `fallbackPollIntervalInMs` serves 2 purposes:

- it allows users to provide an Uplink poll interval if Uplink doesn't
provide one
- it allows users to use a longer poll interval that what's prescribed
by Uplink

The second bullet is how the configuration option is documented, but not
how it was previously implemented. This change corrects the behavior to
respect this configuration if it's provided AND is longer than the
Uplink interval.

- Updated dependencies
\[[`35179f08`](https://togithub.com/apollographql/federation/commit/35179f086ce973e9ae7bb455f7ea7d73cdc10f69)]:
-
[@&#8203;apollo/query-planner](https://togithub.com/apollo/query-planner)[@&#8203;2](https://togithub.com/2).5.2
-
[@&#8203;apollo/federation-internals](https://togithub.com/apollo/federation-internals)[@&#8203;2](https://togithub.com/2).5.2
-
[@&#8203;apollo/composition](https://togithub.com/apollo/composition)[@&#8203;2](https://togithub.com/2).5.2

</details>

<details>
<summary>apollographql/federation (@&#8203;apollo/subgraph)</summary>

###
[`v2.5.2`](https://togithub.com/apollographql/federation/blob/HEAD/subgraph-js/CHANGELOG.md#252)

[Compare
Source](https://togithub.com/apollographql/federation/compare/@apollo/subgraph@2.5.1...@apollo/subgraph@2.5.2)

##### Patch Changes

- Updated dependencies
\[[`35179f08`](https://togithub.com/apollographql/federation/commit/35179f086ce973e9ae7bb455f7ea7d73cdc10f69)]:
-
[@&#8203;apollo/federation-internals](https://togithub.com/apollo/federation-internals)[@&#8203;2](https://togithub.com/2).5.2

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.0.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#301)

[Compare
Source](https://togithub.com/prettier/prettier/compare/3.0.0...3.0.1)

[diff](https://togithub.com/prettier/prettier/compare/3.0.0...3.0.1)

##### Fix cursor positioning for a special case
([#&#8203;14812](https://togithub.com/prettier/prettier/pull/14812) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```js
// <|> is the cursor position

/* Input */
// All messages are represented in JSON.
// So, the prettier.py controls a subprocess which spawns "node {this_file}".
import {<|>  } from "fs"

/* Prettier 3.0.0 */
// All messages are represented in JSON.
// So, the prettier.py <|>controls a subprocess which spawns "node {this_file}".
import {} from "fs"

/* Prettier 3.0.1 */
// All messages are represented in JSON.
// So, the prettier.py controls a subprocess which spawns "node {this_file}".
import {<|>} from "fs"
```

##### Fix plugins/estree.d.ts to make it a module
([#&#8203;15018](https://togithub.com/prettier/prettier/pull/15018) by
[@&#8203;kingyue737](https://togithub.com/kingyue737))

Add `export {}` in `plugins/estree.d.ts` to fix the "File is not a
module" error

##### Add parenthesis around leading multiline comment in return
statement
([#&#8203;15037](https://togithub.com/prettier/prettier/pull/15037) by
[@&#8203;auvred](https://togithub.com/auvred))

<!-- prettier-ignore -->

```jsx
// Input
function fn() {
  return (
    /**
     * @&#8203;type {...}
     */ expresssion
  )
}

// Prettier 3.0.0
function fn() {
  return /**
   * @&#8203;type {...}
   */ expresssion;
}

// Prettier 3.0.1
function fn() {
  return (
    /**
     * @&#8203;type {...}
     */ expresssion
  );
}
```

##### Add support for Vue "Generic Components"
([#&#8203;15066](https://togithub.com/prettier/prettier/pull/15066) by
[@&#8203;auvred](https://togithub.com/auvred))

https://blog.vuejs.org/posts/vue-3-3#generic-components

<!-- prettier-ignore -->

```vue
<!-- Input -->
<script setup lang="ts" generic="T extends Type1 & Type2 & (Type3 | Type4), U extends string | number | boolean"></script>

<!-- Prettier 3.0.0 -->
<script
  setup
  lang="ts"
  generic="T extends Type1 & Type2 & (Type3 | Type4), U extends string | number | boolean"
></script>

<!-- Prettier 3.0.1 -->
<script
  setup
  lang="ts"
  generic="
    T extends Type1 & Type2 & (Type3 | Type4),
    U extends string | number | boolean
  "
></script>
```

##### Fix comments print in `IfStatement`
([#&#8203;15076](https://togithub.com/prettier/prettier/pull/15076) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```js
function a(b) {
  if (b) return 1; // comment
  else return 2;
}

/* Prettier 3.0.0 */
Error: Comment "comment" was not printed. Please report this error!

/* Prettier 3.0.1 */
function a(b) {
  if (b) return 1; // comment
  else return 2;
}
```

##### Add missing type definition for `printer.preprocess`
([#&#8203;15123](https://togithub.com/prettier/prettier/pull/15123) by
[@&#8203;so1ve](https://togithub.com/so1ve))

```diff
export interface Printer<T = any> {
  // ...
+ preprocess?:
+   | ((ast: T, options: ParserOptions<T>) => T | Promise<T>)
+   | undefined;
}
```

##### Add missing `getVisitorKeys` method type definition for `Printer`
([#&#8203;15125](https://togithub.com/prettier/prettier/pull/15125) by
[@&#8203;auvred](https://togithub.com/auvred))

```tsx
const printer: Printer = {
  print: () => [],
  getVisitorKeys(node, nonTraversableKeys) {
    return ["body"];
  },
};
```

##### Add typing to support `readonly` array properties of AST Node
([#&#8203;15127](https://togithub.com/prettier/prettier/pull/15127) by
[@&#8203;auvred](https://togithub.com/auvred))

<!-- prettier-ignore -->

```tsx
// Input
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");

// Prettier 3.0.0
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");
//                  ^ Argument of type '"readonlyArray"' is not assignable to parameter of type '"regularArray"'. ts(2345)

// Prettier 3.0.1
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");
```

##### Add space before unary minus followed by a function call
([#&#8203;15129](https://togithub.com/prettier/prettier/pull/15129) by
[@&#8203;pamelalozano](https://togithub.com/pamelalozano))

<!-- prettier-ignore -->

```less
// Input
div {
  margin: - func();
}

// Prettier 3.0.0
div {
  margin: -func();
}

// Prettier 3.0.1
div {
  margin: - func();
}
```

</details>

<details>
<summary>rollup/rollup (rollup)</summary>

###
[`v3.27.2`](https://togithub.com/rollup/rollup/blob/HEAD/CHANGELOG.md#3272)

[Compare
Source](https://togithub.com/rollup/rollup/compare/v3.27.1...v3.27.2)

*2023-08-04*

##### Bug Fixes

- Revert sourcemap performance improvement for now as it causes issues
with Vite
([#&#8203;5075](https://togithub.com/rollup/rollup/issues/5075))

##### Pull Requests

- [#&#8203;5075](https://togithub.com/rollup/rollup/pull/5075): Revert
perf(sourcemap): lazy compute decoded mappings
([@&#8203;thebanjomatic](https://togithub.com/thebanjomatic))

###
[`v3.27.1`](https://togithub.com/rollup/rollup/blob/HEAD/CHANGELOG.md#3271)

[Compare
Source](https://togithub.com/rollup/rollup/compare/v3.27.0...v3.27.1)

*2023-08-03*

##### Bug Fixes

- Improve performance when generating sourcemaps
([#&#8203;5075](https://togithub.com/rollup/rollup/issues/5075))

##### Pull Requests

- [#&#8203;5075](https://togithub.com/rollup/rollup/pull/5075):
perf(sourcemap): lazy compute decoded mappings
([@&#8203;thebanjomatic](https://togithub.com/thebanjomatic))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/apollographql/apollo-server).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNi4yNy4xIiwidXBkYXRlZEluVmVyIjoiMzYuMjcuMSIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>